"""initial migration

Revision ID: d9f928d472d8
Revises:
Create Date: 2026-02-06 18:24:49.522948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9f928d472d8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.execute(
        "INSERT INTO access_levels (name) \n               VALUES ('User'), ('Premium'), ('Admin')\n               ON CONFLICT (name) DO NOTHING"
    )
    op.create_table(
        "data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("security_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "INSERT INTO data (id, content, security_level) \n               VALUES (1, 'Общедоступная информация', 1), (2, 'Секретная информация', 2)\n               ON CONFLICT DO NOTHING"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('data', 'id'), COALESCE((SELECT MAX(id) FROM data), 1), true)"
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.execute(
        "INSERT INTO users (id, first_name, last_name, email, hashed_password, is_active) \n               VALUES (1, 'ПОЛЬЗОВАТЕЛЬ', 'string', 'user@example.com', '$2b$12$EBtIRd7qO.cPyhtxF2r41.sGCl/.VQfti8geRnRK12imMSfOzG49O', true),\n                      (2, 'АДМИН', 'string', 'user1@example.com', '$2b$12$licaRtyvApARaZqjt/NC3OiPmOjky9r5fkGQ8Otf/CrQoIroIlAke', true),\n                      (3, 'ПРЕМИУМ', 'string', 'user2@example.com', '$2b$12$oziv7Dj/3m7IlT8v/EbP/ut0ETPA6YhgjLK1DxPLPLeidTvw6SKAK', true),\n                      (4, 'ДЛЯ_УДАЛЕНИЯ', 'string', 'user3@example.com', '$2b$12$usamsN20LOHNknBP7A2CQuqulPLGF4cQOA4T/.ru3s7HCGeZ31CGq', true)\n               ON CONFLICT DO NOTHING"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true)"
    )
    op.create_table(
        "user_access_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_level_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_level_id"],
            ["access_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "INSERT INTO user_access_levels (id, user_id, access_level_id) \n               VALUES (1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 1)\n               ON CONFLICT DO NOTHING"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('user_access_levels', 'id'), COALESCE((SELECT MAX(id) FROM user_access_levels), 1), true)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_access_levels")
    op.drop_table("users")
    op.drop_table("data")
    op.drop_table("access_levels")
    # ### end Alembic commands ###
